language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.2
bundler_args: "--without development --path=~/.bundle"
before_script:
  - bundle exec rake db:create db:migrate 
addons:
  postgresql: "9.3"
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: NoZ/CbTKvDZ2JaeA6ObgWZd8QlzBMYdv/9uSZoMsek++MaZz0bah6UgQrETdbukbYLXlshSwFawvZP3CL8HLNou+R7brllQtfStfEcK5T3tzAYe2I1HtHbK/7q+nfHaeJg8CScu2QU9g3Ebt0ehhQ7zQXyralKvcXTrcpS8oHb0=
  run:
    - "rake db:migrate"
  app: git-data-publisher
  on:
    repo: theodi/git-data-publisher
