language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.2
bundler_args: "--without development --path=~/.bundle"
before_script:
- bundle exec rake db:create db:migrate
addons:
  postgresql: '9.3'
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: P0dNrAt/U6fOuVW2yF11+SbGaEMlefaMyQ5ZurbRJdU3eB3BTOscjEayoIjDjFWCtFwLOpTgq+ZJMTdJuHgiJzGIgyVNbAZLaCuvz69rtUSiqoZvSASfVHfwIm11KM8dhUfa1VHXOnbzNCQHx6PO1nDaaYdK3jAHB7GZ1QhFIPc=
  run:
    - "rake db:migrate"
  app: git-data-publisher
  on:
    repo: theodi/git-data-publisher
