language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.2
bundler_args: --without development --path=~/.bundle
before_script: bundle exec rake db:schema:load
notifications:
  irc:
    channels:
      - irc.freenode.net#theodi
    template:
      - '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
